"""
Document & Image Corroboration ReAct Agent

LangGraph state machine (identical structure to backend_1 aml_agent.py):
  agent_node → should_continue → tool_node (loop) | END
"""

import operator
import os
import logging
from typing import Annotated, Any, Dict, List, Optional, TypedDict

from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode
from langchain_openai import ChatOpenAI
from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    HumanMessage,
    SystemMessage,
    ToolMessage,
)

from app.database import prompt_store
from app.agents.doc_tools import (
    list_documents,
    get_document_analysis,
    get_document_risk_score,
    validate_document_structure,
    list_images,
    get_image_analysis,
    verify_image_tampering,
    detect_ai_generated,
    reverse_image_search,
    generate_persona_report,
)

logger = logging.getLogger(__name__)

TOOLS = [
    list_documents,
    get_document_analysis,
    get_document_risk_score,
    validate_document_structure,
    list_images,
    get_image_analysis,
    verify_image_tampering,
    detect_ai_generated,
    reverse_image_search,
    generate_persona_report,
]

DEFAULT_PROMPTS: Dict[str, Dict] = {
    "doc_system": {
        "description": "System prompt for the document corroboration ReAct agent",
        "content": """You are an expert document forensics and corroboration specialist for AML compliance.
You have access to tools to analyse documents and images for authenticity and compliance:
- list_documents: Show all ingested documents
- get_document_analysis: Retrieve full analysis of a specific document
- get_document_risk_score: Get risk score summary for a document
- validate_document_structure: Check document structure and formatting
- list_images: Show all uploaded images
- get_image_analysis: Retrieve image analysis (tampering/AI/metadata)
- verify_image_tampering: Run ELA, copy-move, noise, edge analysis on an image
- detect_ai_generated: Check if an image was generated by AI
- reverse_image_search: Search the web for similar/stolen images
- generate_persona_report: Generate a persona-specific Groq report (executive/compliance/legal/audit/all)

Reason step by step through document authenticity checks. When finished, provide a clear summary
with a risk verdict and recommended actions.""",
    },
    "doc_react_instruction": {
        "description": "ReAct loop format instruction injected per turn",
        "content": """Follow this reasoning format:
Thought: <your reasoning about what to do next>
Action: <tool name and why you chose it>
Observation: <what you learned from the tool result>
... (repeat as needed)
Final Answer: <clear summary with risk verdict>""",
    },
    "doc_routing_hint": {
        "description": "Context injected by the frontend orchestrator before routing",
        "content": "The user is working in the document corroboration module. Focus on document/image authenticity, tampering detection, and compliance validation.",
    },
}

_DEFAULT_SYSTEM_PROMPT = DEFAULT_PROMPTS["doc_system"]["content"]

MAX_ITERATIONS = 10


class DocAgentState(TypedDict):
    messages: Annotated[List[BaseMessage], operator.add]


def _get_llm() -> ChatOpenAI:
    llm = ChatOpenAI(
        model=os.getenv("GROQ_MODEL", "openai/gpt-oss-120b"),
        api_key=os.getenv("GROQ_API_KEY"),
        base_url=os.getenv("GROQ_API_BASE"),
        temperature=0.1,
    )
    return llm.bind_tools(TOOLS)


def _load_system_prompt() -> str:
    row = prompt_store.get_one("doc_system")
    if row and row.get("content"):
        return row["content"]
    return _DEFAULT_SYSTEM_PROMPT


async def agent_node(state: DocAgentState) -> Dict[str, Any]:
    system_prompt = _load_system_prompt()
    messages = [SystemMessage(content=system_prompt)] + state["messages"]
    llm = _get_llm()
    response = await llm.ainvoke(messages)
    return {"messages": [response]}


def should_continue(state: DocAgentState) -> str:
    if len(state["messages"]) > MAX_ITERATIONS * 2:
        return "end"
    last = state["messages"][-1]
    if isinstance(last, AIMessage) and getattr(last, "tool_calls", None):
        return "tools"
    return "end"


def build_doc_agent_graph():
    graph = StateGraph(DocAgentState)
    graph.add_node("agent", agent_node)
    graph.add_node("tools", ToolNode(TOOLS))
    graph.set_entry_point("agent")
    graph.add_conditional_edges("agent", should_continue, {"tools": "tools", "end": END})
    graph.add_edge("tools", "agent")
    return graph.compile()


def _extract_tool_logs(messages: List[BaseMessage]) -> List[Dict[str, Any]]:
    """Extract tool call logs from message history post-hoc."""
    logs = []
    for i, msg in enumerate(messages):
        if isinstance(msg, AIMessage) and getattr(msg, "tool_calls", None):
            for tc in msg.tool_calls:
                for j in range(i + 1, len(messages)):
                    if isinstance(messages[j], ToolMessage) and messages[j].tool_call_id == tc["id"]:
                        output = messages[j].content
                        logs.append({
                            "tool_name": tc["name"],
                            "input": tc.get("args", {}),
                            "output": output[:1000] if isinstance(output, str) else str(output)[:1000],
                        })
                        break
    return logs


def _extract_thought_process(messages: List[BaseMessage]) -> str:
    import json as _json
    parts = []
    for msg in messages:
        if isinstance(msg, AIMessage):
            if msg.content:
                parts.append(f"💭 Thought: {str(msg.content)[:400]}")
            if getattr(msg, "tool_calls", None):
                for tc in msg.tool_calls:
                    args_str = _json.dumps(tc.get("args", {}), default=str)[:150]
                    parts.append(f"🔧 Action: {tc['name']}({args_str})")
        elif isinstance(msg, ToolMessage):
            out = str(msg.content)[:300]
            parts.append(f"👁️ Observation [{msg.name}]: {out}\n")
    return "\n".join(parts)


async def run_doc_agent(
    message: str,
    conversation_history: List[Dict[str, str]],
    context: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Entry point called by the /api/agent route."""
    messages: List[BaseMessage] = []
    for turn in conversation_history:
        if turn["role"] == "user":
            messages.append(HumanMessage(content=turn["content"]))
        else:
            messages.append(AIMessage(content=turn["content"]))
    messages.append(HumanMessage(content=message))

    graph = build_doc_agent_graph()
    result = await graph.ainvoke({"messages": messages})

    all_messages = result["messages"]
    # Find last AIMessage with non-empty text content (no tool calls)
    response_text = ""
    for msg in reversed(all_messages):
        if isinstance(msg, AIMessage) and msg.content and not getattr(msg, "tool_calls", None):
            response_text = msg.content if isinstance(msg.content, str) else str(msg.content)
            break

    if not response_text:
        # All AI messages were tool-call-only; do a final summarization call
        system_prompt = _load_system_prompt()
        summary_messages = [SystemMessage(content=system_prompt)] + all_messages + [
            HumanMessage(content="Based on the information gathered above, provide a concise summary answer.")
        ]
        llm_plain = ChatOpenAI(
            model=os.getenv("GROQ_MODEL", "openai/gpt-oss-120b"),
            api_key=os.getenv("GROQ_API_KEY"),
            base_url=os.getenv("GROQ_API_BASE"),
            temperature=0.1,
        )
        summary_response = await llm_plain.ainvoke(summary_messages)
        response_text = summary_response.content if isinstance(summary_response.content, str) else str(summary_response.content)

    return {
        "response": response_text,
        "tool_calls": _extract_tool_logs(all_messages),
        "thought_process": _extract_thought_process(all_messages),
    }
